package com.aji.coba.controller;

import com.aji.coba.model.User;
import com.aji.coba.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // this means that this class is a Controller
@RequestMapping(path="/demo") // this means URL's start with/  demo (after Application path)
public class MainController {
    @Autowired // this mean to get the bean called usedRepository
        // which is auto-generated by spring, we will use it to handle the data
    private UserRepository userRepository;

    @PostMapping(path="/add") 
    public @ResponseBody User addNewUser (@RequestBody User user){
        return userRepository.save(user);
    }  

    @GetMapping(path="/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        return userRepository.findAll();       
    }
}